// Compute Shader 至少要包含一个内核函数，通过 #pragma kernel funcitonName 来声明；可以有多个内核函数
#pragma kernel CSMain   

// Create a RenderTexture with enableRandomWrite flag and set it with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    // Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
    Result[id.xy] = float4(1, 1, 0, 1.0);
}
