// Compute Shader 至少要包含一个内核函数，通过 #pragma kernel funcitonName 来声明；可以有多个内核函数
#pragma kernel CSMain   

// Create a RenderTexture with enableRandomWrite flag and set it with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 dtid : SV_DispatchThreadID)
{
    float r = dtid.y / 1024.0;
    float g = (1.0 - dtid.x / 1024.0) * r;
    float b = (1.0 - dtid.x / 1024.0) * r;
    
    Result[dtid.xy] = float4(r, g, b, 1.0);
}
